[contrib/cristal] make it compile out of the box
previously we got

/bin/bash ../../libtool  --tag=CC   --mode=link gcc -I../.. -I../../hkl -I../../third-party -DPKGDATA=\""/usr/local/share/hkl"\" -fPIC -DPIC  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -I/usr/include/hdf5/serial  -Wall -g -O2 -lcglm  -lglib-2.0  -L/usr/lib/x86_64-linux-gnu/hdf5/serial -lhdf5   -o little-data little-data.o xrays/libhkl-xrays.la
libtool: link: gcc -I../.. -I../../hkl -I../../third-party -DPKGDATA=\"/usr/local/share/hkl\" -fPIC -DPIC -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/hdf5/serial -Wall -g -O2 -o little-data little-data.o  -L/usr/lib/x86_64-linux-gnu/hdf5/serial xrays/.libs/libhkl-xrays.a -lcglm -lglib-2.0 -lhdf5
/usr/bin/ld: xrays/.libs/libhkl-xrays.a(xrays-image.o): undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line